name: sc-controller
base: core18 # the base snap is the execution environment for this snap
version: '0.4.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Driver, mapper and GUI for Steam Controller, DS4 and similar controllers.
description: |
  Allows setup, configuration and use of Steam Controller(s) without ever launching Steam. Supports switchable profiles, sticks, pads, gyroscope input, haptic feedback and in-game rumble support. OSD, menus and on-screen keyboard for desktop and in games. Automatic profile switching based on active window. Emulates Xbox360 controller, mouse, trackball and keyboard and much more.

  Important note! - It is essential to install the Steam Controller udev rules on your system to access your device. Ubuntu users should run "sudo apt install steam-devices".
  
  No attempt has yet been made to implement bluetooth functionality into this snap. Neither has it been tested on non-Steam controllers. Please file issues at https://github.com/mcphail/sc-controller-snap if you would be interested in helping to test these features.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  main:
    source: https://github.com/kozec/sc-controller/archive/v0.4.8.tar.gz
    plugin: python
    python-version: python2
    organize:
      bin: /usr/bin
      share: /usr/share
    stage-packages:
      - python-gobject
      - python-gi
      - libgtk-3-0
      - gir1.2-gtk-3.0
      - python-gi-cairo
      - gir1.2-rsvg-2.0
      - xinput
      - python-pylibacl
      - python
      - python-evdev
      - libusb-1.0-0
      - linux-libc-dev

  cleanup:
    after: [main]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  sc-controller:
    extensions: [gnome-3-28]
    command: $SNAP/usr/bin/sc-controller
    plugs: [raw-usb, uinput]

layout:
  /usr/bin/python:
    symlink: $SNAP/usr/bin/python
  /usr/include/linux/input.h:
    symlink: $SNAP/usr/include/linux/input.h
  /usr/include/linux/input-event-codes.h:
    symlink: $SNAP/usr/include/linux/input-event-codes.h
