name: sc-controller
base: core18 # the base snap is the execution environment for this snap
version: '0.4.6.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Driver, mapper and GUI for Steam Controller, DS4 and similar controllers.
description: |
  Allows to setup, configure and use Steam Controller(s) without ever launching Steam. Supports switchable profiles, sticks, pads, gyroscope input, haptic feedback and in-game rumble support. OSD, menus and on-screen keyboard for desktop ans in games. Automatic profile switching based on active window. Emulates Xbox360 controller, mouse, trackball and keyboard and much more.

  Note - this snap will not be functional until support for accessing /dev/uinput comes to snapd. Brave pioneers can follow the instructions at https://forum.snapcraft.io/t/best-way-to-access-dev-uinput/16242/7 in the meantime.

  Note 2 - It is essential to install the Steam Controller udev rules on your system to access your device. Ubuntu users should run "sudo apt install steam-devices".

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
architectures:
  - build-on: amd64
    run-on: amd64

parts:
  deb:
    source: https://download.opensuse.org/repositories/home:/kozec/xUbuntu_18.04/amd64/sc-controller_0.4.6.1_amd64.deb
    plugin: dump
    stage-packages:
      - python-gobject
      - python-gi
      - libgtk-3-0
      - gir1.2-gtk-3.0
      - python-gi-cairo
      - gir1.2-rsvg-2.0
      - xinput
      - python-pylibacl
      - python
      - libusb-1.0-0
      - linux-libc-dev

apps:
  sc-controller:
    extensions: [gnome-3-28]
    command: $SNAP/usr/bin/sc-controller
    plugs: [raw-usb]

layout:
  /usr/bin/python:
    symlink: $SNAP/usr/bin/python
  /usr/include/linux/input.h:
    symlink: $SNAP/usr/include/linux/input.h
  /usr/include/linux/input-event-codes.h:
    symlink: $SNAP/usr/include/linux/input-event-codes.h
